#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
# Source: http://blog.mcpolemic.com/2016/10/01/reconciling-tmux-and-ssh-agent-forwarding.html
#:wq
if test "$SSH_AUTH_SOCK" ; then
	ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
