if [[ "$OSTYPE" == "darwin"* ]] ; then
  case "$(uname -m)" in
    x86_64)
      eval "$(/usr/local/bin/brew shellenv)"
      ;;
    arm64)
      eval "$(/opt/homebrew/bin/brew shellenv)"
      ;;
  esac
fi

if [ -f ~/.bashrc ];
then
	source ~/.bashrc
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
