#!/bin/bash

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Configure SSH to use 1Password SSH Agent
#
# Pre-requisites: Turn on 1Password SSH Agent
#   - Open 1Password / Preferences / Developer
#   - Tick the checkboxes:
#       - "Use SSH Agent"
#       - "Display key names when authorizing connections"
#
# See: https://developer.1password.com/docs/ssh/get-started/
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if [[ "$OSTYPE" != "darwin"* ]]; then
  exit 0
fi

OP_DIR=~/.1password
OP_SSH_AGENT_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
OP_SSH_AGENT_SOCK_SYMLINK=$OP_DIR/agent.sock

if [[ ! -S "$OP_SSH_AGENT_SOCK" ]]; then
  echo '1Password SSH-Agent not enabled.'
  echo 'Open 1password 8, open "Preferences / Developer" then check "Use SSH Agent"'
  exit 0
fi

if [[ ! -d "$OP_DIR" ]]; then
  mkdir     "$OP_DIR"
  chmod 700 "$OP_DIR"
fi

if [[ ! -S "$OP_SSH_AGENT_SOCK_SYMLINK" ]]; then
  ln -s "$OP_SSH_AGENT_SOCK" "$OP_SSH_AGENT_SOCK_SYMLINK"
fi

exit 0
