#!/bin/bash

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Remove crdential.helper from the git config 
#  when we are not on a Mac
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Removing credential.helper from the global git config because we only need it on a Mac"
  git config --global --unset credential.helper
fi

