#!/bin/bash

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Install hub
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~

type hub >/dev/null 2>&1 && exit 0


# hub not installed, installing it

case $OSTYPE in
  darwin*)
    brew install hub
  ;;
  linux*)
    install_hub
  ;;
esac

install_hub() {
  mkdir -p $HOME/bin \
    && cd $HOME/tmp \
    && curl -LO https://thoughtbot.github.io/rcm/dist/rcm-1.3.1.tar.gz \
    &&  sha=$(shasum -a 256 rcm-1.3.1.tar.gz | cut -f1 -d' ') \
    &&  [ "$sha" = "9c8f92dba63ab9cb8a6b3d0ccf7ed8edf3f0fb388b044584d74778145fae7f8f" ] \
    && tar -xvf rcm-1.3.1.tar.gz \
    &&  cd rcm-1.3.1 \
    &&  ./configure --prefix=$HOME/local \
    && make \
    && make install
}
