#!/bin/bash

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create some of the vim folders
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

VIM_FOLDERS=(~/.vim/backup ~/.vim/swap ~/.vim/undo)


mkdir -p ~/.vim

for folder in "${VIM_FOLDERS[@]}"; do
  if [[ ! -d "$folder" ]]; then
    mkdir "$folder"
    chmod go= "$folder"
  fi
done


